language: go

go:
  - master

install:
  - go get ./...
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/haya14busa/goverage

script:
  - go vet ./...
  - diff <(goimports -d .) <(printf "")
  - diff <(golint ./...) <(printf "")
  - goverage -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./build.sh mock-generator

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - "dist/darwin_386_mock-generator.zip"
    - "dist/darwin_64_mock-generator.zip"
    - "dist/linux_386_mock-generator.zip"
    - "dist/linux_64_mock-generator.zip"
    - "dist/windows_386_mock-generator.zip"
    - "dist/windows_64_mock-generator.zip"
  on:
    all_branches: true
    tags: true
